baseURL = "https://vikaschouhan.com/"
languageCode = "en-us"
title = "Vikas Chouhan"
theme = "hugo-resume"

[params]
    firstName = "Vikas"
    lastName = "Chouhan"
    phone = "+919611663497"
    phone_ex = "+91-9611663497"
    contactNote = "Software Architect"
    profileImage = "img/profile-pic.jpg"
    email = "presentisgood@gmail.com"
    description = "Software/AI engineer"
    favicon = "/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/vikas-chouhan-4a36829/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/vikaschouhan/"
